# Generated by Django 5.2.7 on 2025-11-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='graduate',
            field=models.TextField(blank=True, verbose_name='Освіта'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='По-батькові'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='work_experience',
            field=models.TextField(blank=True, verbose_name='Досвід роботи'),
        ),
    ]
