# Generated by Django 5.1.13 on 2025-10-26 09:08

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='UA', unique=True, verbose_name='Телефон'),
        ),
    ]
