# Generated by Django 5.2.7 on 2025-12-15 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevix', '0002_trainer_graduate_trainer_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='specialization',
            field=models.CharField(choices=[('mma', 'ММА'), ('boxing', 'Бокс'), ('massage', 'Масаж'), ('fitness', 'Фітнес'), ('yoga', 'Йога'), ('crossfit', 'Кросфіт')], default='fitness', max_length=50, verbose_name='Спеціалізація'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Тривалість (години)')),
                ('category', models.CharField(choices=[('group_training', 'Групове тренування'), ('personal_training', 'Персональне тренування'), ('massage', 'Масаж')], max_length=50, verbose_name='Категорія')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='elevix.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'db_table': 'services',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва плану')),
                ('plan_type', models.CharField(choices=[('single', 'Разове'), ('package', 'Пакет')], max_length=20, verbose_name='Тип плану')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (грн)')),
                ('sessions_count', models.PositiveIntegerField(blank=True, help_text='Залиште порожнім для разового', null=True, verbose_name='Кількість занять')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Знижка (%)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Базовий план')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='elevix.service', verbose_name='Послуга')),
            ],
            options={
                'verbose_name': 'Тарифний план',
                'verbose_name_plural': 'Тарифні плани',
                'db_table': 'pricing_plans',
                'ordering': ['service', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(verbose_name='Дата та час бронювання')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна сума (грн)')),
                ('sessions_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Всього занять')),
                ('sessions_remaining', models.PositiveIntegerField(blank=True, null=True, verbose_name='Залишок занять')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('pricing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='elevix.pricingplan', verbose_name='Тарифний план')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='elevix.service', verbose_name='Послуга')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
                'db_table': 'bookings',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=250, verbose_name='Текст особливості')),
                ('icon', models.CharField(blank=True, help_text='Назва іконки або клас', max_length=50, verbose_name='Іконка')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='elevix.service', verbose_name='Послуга')),
            ],
            options={
                'verbose_name': 'Особливість послуги',
                'verbose_name_plural': 'Особливості послуг',
                'db_table': 'service_features',
                'ordering': ['service', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, "П'ятниця"), (5, 'Субота'), (6, 'Неділя')], verbose_name='День тижня')),
                ('start_time', models.TimeField(verbose_name='Час початку')),
                ('end_time', models.TimeField(verbose_name='Час закінчення')),
                ('max_participants', models.PositiveIntegerField(default=1, help_text='Для групових тренувань', verbose_name='Макс. учасників')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='elevix.trainer', verbose_name='Тренер')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='elevix.service', verbose_name='Послуга')),
            ],
            options={
                'verbose_name': 'Розклад',
                'verbose_name_plural': 'Розклади',
                'db_table': 'schedules',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('trainer', 'day_of_week', 'start_time')},
            },
        ),
    ]
