# Generated by Django 5.2.7 on 2025-12-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevix', '0003_alter_trainer_specialization_service_pricingplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Питання (FAQ)',
                'verbose_name_plural': 'Питання (FAQ)',
                'db_table': 'faqs',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
